### ISSUE TITLE
Inserir um mapa de localização do setor

### ISSUE THREAD

**Issue by denis-or** [rafapereirabr/todos_setores#3]
Oi Rafael. Achei muito interessante seu projeto.

Pensei que seria legal inserir um mapa de localização pontuando o centróide do setor censitário. Não sei se ficaria legal em todos os setores, mas fiz algo como:
<img src='https://user-images.githubusercontent.com/49842454/211174027-72696c11-ffbb-4d0d-bd8a-d8f3cd2de468.png' width='500'>

As alterações seriam na função save_image:

``` r
  # download boundaries of the brazilian states 
  br <- sf::read_sf("https://github.com/ipeaGIT/geobr/releases/download/v1.7.0/country_2020_simplified.gpkg")
  
  ppoint <- sf::st_transform(sf::st_centroid(temp_ct2), crs = sf::st_crs(br))

  # save image to tempfile
  tempd <- tempdir()
  image_file <- paste0(tempd, '/image_383.png')
  # image_file <- paste0(tempd, '/image_', i, '.png')
  # browseURL(image_file)

  png(image_file, res = 300, width = 15, height = 15*r, units = 'cm') 

  layout(mat = matrix(c(1, 2, 3, 2), nrow = 2, ncol = 2, byrow = TRUE), widths = c(1, 3))
  par(oma = c(0,0,0,0), mar = c(0,0,0,0), mai = c(0,0,0,0))

  # par(mfrow=c(1,2))
  plot(x = sf::st_geometry(br), col = "#FAFAFA", border = "#BABABA", reset = FALSE)
  plot(x = sf::st_geometry(subset(br,code_state == temp_ct2$code_state)), add=TRUE, col = "#BABABA", border = "#BABABA")
  plot(x = sf::st_geometry(ppoint),  add=TRUE, cex = 2, pch = 19, col = "red")
  
  terra::plotRGB(temp_plot)
  dev.off()

```

Mas como o visual dos setores podem variar, não sei se ficaria bom em qualquer setor. Mas fica a ideia. O projeto está em andamento então seria legal pra próxima.

**Comment by rafapereirabr** [comment]
Oi Denis. Muito obrigado pela sugestão. Eu cheguei a pensar nisso mas acabei desistindo por diferentes razoes. Como voce mesmo disse, o formato dos setores é muito variado. Então seria muito dificil programaca uma posição dinâmica. Além disso, isso acabaria tirando o foco do setor censitario em si. E se a ideia é inseir contexto de localização, essa inf o já é indicaida no tweet com o estado e o link para o google maps. Mas enfim, super obrigado pela sugestão. fico contente de que tenha gostado do bot a ponto de se protificar e dar uma sugestao legal. obrigado.

**Comment by rafapereirabr** [comment]
obrigado mesmo pela sugestao. Fechando o issue por enquanto
